### ISSUE TITLE
Tooltip a bit off center when added to icon <i>

### ISSUE THREAD

**Issue by 4tron** [circlingthesun/angular-foundation-6#11]
![tooltip-position](https://cloud.githubusercontent.com/assets/11210554/15828101/50c68eba-2c0e-11e6-855b-73088f654604.png)

` <i class="icon-facebook" tooltip-placement="top" tooltip="Facebook"></i>`

**Comment by giovanniorigins** [comment]
It's more than just icons, generally anything under the width of 70px

**Comment by giovanniorigins** [comment]
Changing lines 2126 and 2138 in the angular-foundation.js file fixed this issue for me. The left position was not taking the tooltip's width and the objects width into account
Replace:
`left: position.left`
With:
`left: position.left - ttWidth / 2 + position.width / 2`

**Comment by 4tron** [comment]
That kind of works but it is dependent on the size of the icon.

**Comment by circlingthesun** [comment]
@giovanniorigins thanks for the fix, I've rolled it into the latest release.
