### ISSUE TITLE
No close-on-click for reveal

### ISSUE THREAD

**Issue by 4tron** [circlingthesun/angular-foundation-6#13]
Currently there is no option to set the `close on click` as outlined in the foundation 6 documentation

http://foundation.zurb.com/sites/docs/reveal.html#js-options

There is a work around to set the `backdrop:false` which then works like the `close on click`. Not ideal. Functionality is fairly useful for confirm based reveals.

**Comment by circlingthesun** [comment]
Added via 14f418a
