### ISSUE TITLE
Reveal Modal - position

### ISSUE THREAD

**Issue by victorsosa** [circlingthesun/angular-foundation-6#15]
Hi, 
I am using a modal in my app, how I could move the position of modal? I don't want it in the center.

thanks,

**Comment by circlingthesun** [comment]
The foundation CSS determines the position of the modal. So you should be able to change the position by modifying the CSS.

**Comment by victorsosa** [comment]
ok, but which css class and which properties (top, left I suppose)? I don't know which class I have to overwrite so I can position the modal relative to an element.

**Comment by circlingthesun** [comment]
You should have a look at https://github.com/zurb/foundation-sites/blob/develop/scss/components/_reveal.scss. You could also apply your own class to the modal via `windowClass`.

**Comment by victorsosa** [comment]
thanks, I did it using the windowClass parameter :+1:
