### ISSUE TITLE
Bower missing

### ISSUE THREAD

**Issue by Jaspur** [circlingthesun/angular-foundation-6#2]

**Comment by Opticsponge** [comment]
@Jaspur workaround I used
`bower install --save circlingthesun/angular-foundation-6`

**Comment by Jaspur** [comment]
Yea, then it's missing the dist/compiled files to use it easily with gulp

**Comment by Opticsponge** [comment]
arghh you are right, I hadn't got that far yet.

**Comment by iamchairs** [comment]
I made a pull request for this.

https://github.com/circlingthesun/angular-foundation-6/pull/4/commits

In the meantime. You can this to your bower dependencies:

`"angular-foundation-6": "git://github.com/iamchairs/angular-foundation-6.git#7595974805899735538b5f7141b0fd59ea6e9dcb"`

**Comment by circlingthesun** [comment]
@iamchairs, thanks for the PR. I'm sure if I'm happy with including build artifacts in the main repo. It's certainly the simplest way to support bower. Angular-foundation and Angular both have separate repos dedicated to bower. I think I prefer that approach but it might not be worth the effort. Let me mull it over and get back to you.

**Comment by iamchairs** [comment]
@circlingthesun Foundation and Angular may have bower but this repo doesn't. I don't see what you're saying.

**Comment by circlingthesun** [comment]
@iamchairs, I've added the bower file from your PR and updated the build. It should also be on the bower registry soon. I'm not sure how long they take to update.

PS. I was referencing Angular-foundation and Angular's choices as to how they support bower. Both have have a separate repo for bower with build artefacts. I prefer this approach but I've decided it's too much overhead.

**Comment by circlingthesun** [comment]
`bower install angular-foundation-6`
