### ISSUE TITLE
Typeahead

### ISSUE THREAD

**Issue by looorent** [circlingthesun/angular-foundation-6#20]
First of all, thank you very much for creating this project!

I was wondering whether the `typeahead` component is planned?

Best regards

**Comment by circlingthesun** [comment]
Hey @looorent,

I don't have any plans to implement it at this stage. I'm personally using angucomplete-alt in my projects at the moment.

Regards
Rickert

**Comment by looorent** [comment]
Thank you, it works like a charm.

Regards
Lorent
