### ISSUE TITLE
Dropdown Menu (mm.foundation.dropdownMenu) not working?

### ISSUE THREAD

**Issue by vkatsar** [circlingthesun/angular-foundation-6#22]
I have an issue when trying to use the dropdown menu.

my html file includes
`
//cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation.css" rel="stylesheet
bower_components/angular-foundation-6/dist/angular-foundation.js
`

my app.js
------------------------------------------------------
`angular.module('betterflyApp', [
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ngStorage',
  'btford.socket-io',
  'ui.router',
  'ngDialog',
  'mm.foundation'
])....`
i am having a directive with the navigation menu

html of the menu
`<ul class="dropdown menu" data-dropdown-menu>
  <li>
    <h1><a class="logo" ui-sref="main"><img data-interchange="[assets/images/logot.png, small], [assets/images/logot.png, medium],[assets/images/logo.png, large]," /></a></h1>
  </li>
  <li>
    <a>Explore</a>
    <ul class="menu">
      <li>
        <a href='#'>Products</a>
      </li>
      <li>
        <a href='#'>Campaigns</a>
      </li>
    </ul>
  </li>
  <li>
    <a href="#">How it works</a>
    <ul class="menu">
      <li>
        <a href='#'>What we do</a>
      </li>
      <li>
        <a ui-sref="faq">F.A.Q.</a>
      </li>
    </ul>
  </li>
  <li><a href="#">Blog</a></li>
</ul>`

When i have the .dropdown class i have this result 
![screen shot 2016-08-18 at 02 47 44](https://cloud.githubusercontent.com/assets/1533478/17757376/e8de8478-64ee-11e6-91a7-ef861e55bf5a.png)

and the dropdown is not working

if i remove the .dropdown class i have this result
![screen shot 2016-08-18 at 02 48 03](https://cloud.githubusercontent.com/assets/1533478/17757387/062f8cb6-64ef-11e6-830e-ca6e80ad1feb.png)

This code is working well with foundation 6 for sites 

I tried to use other components like accordion and that works perfect

**Comment by vkatsar** [comment]
finally found it

for some reason i had to remove 

 <html class="no-js"> 

and works...

**Comment by circlingthesun** [comment]
:+1:
