### ISSUE TITLE
angular 1.5.x component modal 

### ISSUE THREAD

**Issue by freeman29** [circlingthesun/angular-foundation-6#27]
Hi, 

Kudos for the hard work on this, your awesome. I notice the modal is still using the controller approach, is there a way to make it component approach? Like the following:

`var params = {
       component: 'myModalComponent',
            resolve: {
                items: function() {
                    return ctrl.items;
                },
            }` 

or 

`var params = {
       component: '<myModalComponent items="myModalComponent" /><myModalComponent>',
            }`

**Comment by circlingthesun** [comment]
There is no reason you can't use components.

```
$modal.open({
   template: '<myModalComponent items="$ctrl.items" /><myModalComponent>',
   controllerAs: '$ctrl',
   controller: function() {
     this.items = ['item1', 'item2'];
   }
})
```

**Comment by freeman29** [comment]
Sorry for the delayed reply @circlingthesun. Thanks for your code snippet above, it's working great.

Just a question, is the modal open has the resolve method for component bindings like the UI bootstrap implementation?

**Comment by circlingthesun** [comment]
I'm not sure how the bootstrap version works, but the modal won't open
until the values/promises in the resolve object has been resolved. You can
also inject what is returned from the resolve object into your controller
by key. You can then to pass them onto your component.

**Comment by freeman29** [comment]
Ok got it. Thanks again @circlingthesun. Closing this ticket now.
