### ISSUE TITLE
Content location in Vertical Tabs

### ISSUE THREAD

**Issue by RomanBorysenok** [circlingthesun/angular-foundation-6#28]
Hello,

Thank you for your effort for delivering foundation 6 for angular.
I noticed that content location in Vertical tabs in "angular-foundation-6" differs from "angular-foundation". Right now it's located below the tabs, but previously it was located right after the tabs (screenshots attached). Is it desired behavior? As for me, such variant of content location is not very useful and it seems like a bug.

Thank you in advance!

![foundation5](https://cloud.githubusercontent.com/assets/21261854/18477991/549d089e-79d8-11e6-83d2-3b6094f28af9.jpg)
![foundation6](https://cloud.githubusercontent.com/assets/21261854/18477992/54b88fd8-79d8-11e6-8c48-29b12dce59b8.jpg)

**Comment by circlingthesun** [comment]
Yep, that's a bug. A PR would be greatly appreaciated as I can't really look into that right away.
