### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by freeman29** [circlingthesun/angular-foundation-6#30]
Hi,

Can I import this now using ES6? if yes, how?

Thanks,

**Comment by circlingthesun** [comment]
@freeman29 there is nothing preventing you from importing this via ES6 module loading syntax. It will probably look something like ```import 'angular-foundation';``` depending on how your project is set up.

**Comment by circlingthesun** [comment]
I assume that this is resolved.

**Comment by freeman29** [comment]
yeah, sorry for the late reply. been busy with new projects.
