### ISSUE TITLE
Modal not working with BUILD

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [circlingthesun/angular-foundation-6#32]
I am currently using angular version 1.5.3

Foundation modal works well in development environment. 
But after generating dist then build breaks.
Says "Unknown provider: bProvider <- b"

**Comment by pushkardeshmukh1992** [comment]
I also tried previous versions of angular. But still couldn't figure it out.

**Comment by circlingthesun** [comment]
That's a minification issue. If you are using the source files need to run ngAnnotate on them first.

**Comment by circlingthesun** [comment]
I'm assuming this issue is resolved.
