### ISSUE TITLE
Vertical tabs not working

### ISSUE THREAD

**Issue by moroz-off** [circlingthesun/angular-foundation-6#36]
Do not display vertical tabs can be seen in the attachment, a screen shot is made with http://circlingthesun.github.io/angular-foundation-6/

![2016-11-25 13 28 40](https://cloud.githubusercontent.com/assets/20340539/20622485/82ebe918-b31c-11e6-8b5d-836096806f64.png)

Template code is also true:

`angular.module("mm.foundation.tabs").run(["$templateCache", function ($templateCache) {
        $templateCache.put("template/tabs/tab.html", "<li class=\"tabs-title\" ng-class=\"{\'is-active\': active}\">\n  <a ng-click=\"select()\" ng-attr-aria-selected=\"{{active}}\" tab-heading-transclude>{{heading}}</a>\n</li>\n");
        $templateCache.put("template/tabs/tabset-horizontal.html", "<div class=\"tabbable\">\n  <ul class=\"tabs\" ng-transclude></ul>\n  <div class=\"tabs-content\">\n    <div class=\"tabs-panel\"\n      ng-repeat=\"tab in tabs\"\n      ng-class=\"{\'is-active\': tab.active}\">\n      <div tab-content-transclude=\"tab\"></div>\n    </div>\n  </div>\n</div>\n");
        $templateCache.put("template/tabs/tabset-vertical.html", "<div class=\"tabbable row collapse\">\n  <div class=\"medium-3 columns\">\n    <ul class=\"tabs vertical\" ng-transclude></ul>\n  </div>\n  <div class=\"medium-9 columns\">\n    <div class=\"tabs-content vertical\">\n      <div class=\"tabs-panel\"\n        ng-repeat=\"tab in tabs\"\n        ng-class=\"{\'is-active\': tab.active}\">\n        <div tab-content-transclude=\"tab\"></div>\n      </div>\n    </div>\n  </div>\n</div>\n");
}]);`

**Comment by circlingthesun** [comment]
@moroz-off, due to an issue with #35, you have you specify vertical="vertical" for it to work. I'll fix this when I have a moment. PR is also welcome ;)

**Comment by moroz-off** [comment]
Thank you)
