### ISSUE TITLE
Modal is not working in IE

### ISSUE THREAD

**Issue by sugarsaixan** [circlingthesun/angular-foundation-6#40]
Modal not working in IE. Error is "Object doesn't support property or method 'find'"

**Comment by circlingthesun** [comment]
Have you tried including a shim such as https://github.com/paulmillr/es6-shim?

**Comment by sugarsaixan** [comment]
I am using babel {"presets": ["es2015"]}.  Should i change babel to es6-shim ?

**Comment by circlingthesun** [comment]
Babel only transforms your code, it doesn't polyfill missing API's. You still need the 'find' function on array objects that is missing in IE. Including es6 shim or core-js will give you this.

**Comment by circlingthesun** [comment]
See https://github.com/zloirock/core-js#ecmascript-6-array or https://github.com/zloirock/core-js/blob/v2.4.1/modules/es6.array.find.js

**Comment by sugarsaixan** [comment]
It works. Thank you for your support. @circlingthesun

**Comment by circlingthesun** [comment]
No problem :)
