### ISSUE TITLE
Any plans on including the orbit carrousel?

### ISSUE THREAD

**Issue by ro8in** [circlingthesun/angular-foundation-6#44]
Are there any plans to also include the foundation orbit carrousel? 

I don't want to include another whole framework like the foundation javascript or jquery just for a carrousel.

**Comment by circlingthesun** [comment]
I have actually written a component for this that I'm using on https://bookem.co.za/. I've not added it here yet because its a bit beta and may require a tiny bit of non foundation css. If you'd like I guess I could include it.

**Comment by ro8in** [comment]
That would be awesome yes please.. Don't mind fiddling around a bit with the css, always better then including another 20 javascript files just to get a working carousel. Really don't want to bother writing one from scratch at the moment, just want to finish this project already haha.

**Comment by circlingthesun** [comment]
Just released 0.11.2. http://circlingthesun.github.io/angular-foundation-6/#/orbit

**Comment by ro8in** [comment]
Dude!! Thats soo fast, thanks allot!!!

gonna try it out right now.

**Comment by ro8in** [comment]
I'm getting when using the new release :/

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.1/$injector/modulerr?p0=appname&p1=Error%3A…20at%20Mc%20(http%3A%2F%2Fbrandbuy%3A4232%2Fjs%2Fangular.min.js%3A21%3A332)
    at angular.min.js:6
    at angular.min.js:41
    at q (angular.min.js:7)
    at g (angular.min.js:40)
    at eb (angular.min.js:45)
    at c (angular.min.js:21)
    at Mc (angular.min.js:21)
    at pe (angular.min.js:20)
    at angular.min.js:329
    at HTMLDocument.b (angular.min.js:37)

**Comment by circlingthesun** [comment]
You need the 'angular-touch' module.

**Comment by ro8in** [comment]
yep that was the problem, thanks!

**Comment by ro8in** [comment]
I added it to my project, and it kinda works..

Only when i click the bullets it just jumps to the next frame instead of sliding. Is there something i'm missing?

**Comment by circlingthesun** [comment]
```css
.orbit-container {
  transition: all 0.5s cubic-bezier(0.65, 0.05, 0.36, 1);
}
```

**Comment by ro8in** [comment]
Ok call me stupid xD

Thanks works perfectly now!

**Comment by circlingthesun** [comment]
Well, this version works a tiny bit different to the original foundation one, so that's why the animation from the original component doesn't kick in.

**Comment by ro8in** [comment]
Well like this is good too.. 

Keep up the good work! 
I was half way my project when i realized foundation JS and Angular don't play well together. Only realized this until i wanted to add some Modal popups. You really saved me here from having to go back to scratch. I could even kick out jquery and all that saving me like 500kb of javascript loading on each page.

**Comment by circlingthesun** [comment]
Glad it all worked out :) :+1:
