### ISSUE TITLE
Modal not working in the Demo Page with IE

### ISSUE THREAD

**Issue by mpetrucc** [circlingthesun/angular-foundation-6#45]
Hallo,
the modal doesn't work in the [demo page](https://circlingthesun.github.io/angular-foundation-6/#/modal), as well in my project.
The error is

> TypeError: L'oggetto non supporta la proprietà o il metodo 'find'

(sorry for Italian but I think you can understand)

Maybe there's a problem with other components\directives too.

How can I integrate modal correctly ?

**Comment by circlingthesun** [comment]
Have a look at https://github.com/circlingthesun/angular-foundation-6/issues/40

**Comment by mpetrucc** [comment]
Thanks ! i've seen you've updated the demo page too.

**Comment by circlingthesun** [comment]
Yup, thanks for pointing that out :)
