### ISSUE TITLE
[$injector:modulerr] error in plunker

### ISSUE THREAD

**Issue by imdivakar92** [circlingthesun/angular-foundation-6#46]
Hi @circlingthesun 

Can you clear this error in plunker demo [http://plnkr.co/edit/?p=preview](url)
![err](https://cloud.githubusercontent.com/assets/16860328/22960892/8b0f453c-f367-11e6-9e07-a8a9d092e946.png)

**Comment by circlingthesun** [comment]
If you just upgraded you need load angular-touch before loading
angular-foundation. Alternatively any 0.10.x version doesn't require this.

**Comment by circlingthesun** [comment]
Oh, right, this is the plunker. I need to add angular-touch to that.

**Comment by circlingthesun** [comment]
This should be fixed now. Thanks for reporting :+1:
