### ISSUE TITLE
Uncaught Error: [$injector:modulerr] when loading mm.foundation module

### ISSUE THREAD

**Issue by rgecy** [circlingthesun/angular-foundation-6#47]
I cannot figure out what is going on with this.  I have even stripped my app down to try and load this and I keep getting this error.  I am using 0.11.3, angular 1.5.10, and foundation 6.2.3

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=myApp&p1=Error%3A%…bileapps.bcgov.net%2Flibs%2Fangularjs%2F1.5.10%2Fangular.min.js%3A21%3A332)
    at angular.min.js:6
    at angular.min.js:40
    at q (angular.min.js:7)
    at g (angular.min.js:39)
    at fb (angular.min.js:43)
    at c (angular.min.js:21)
    at Gc (angular.min.js:21)
    at se (angular.min.js:20)
    at angular.min.js:323
    at HTMLDocument.b (angular.min.js:192)

```
<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="HandheldFriendly" content="true">
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<title>COSY</title>
	<link rel="stylesheet" href="/libs/foundation/6.2.3/css/foundation.css"/>
	<script src="/libs/angularjs/1.5.10/angular.min.js"></script>
	<script src="/libs/angular-foundation/mm-foundation-0.11.3.js"></script>
	<script src="js/cosyApp.js"></script>
</head>
<body ng-app="myApp">
</body>
</html>
```

```
(function () {
	'use strict';
	angular.module('myApp', ['mm.foundation']);
})();
```

**Comment by circlingthesun** [comment]
It's likely that you haven't loaded angular-touch which is required because of the new orbit component.

**Comment by rgecy** [comment]
Yep! That did it! Thank you. Maybe that should be added to the docs and getting started website so it is listed as a dependency.  I have been fighting with this for 4 or 5 hours!

Thanks again for the quick response!

Robert

**Comment by circlingthesun** [comment]
Sure, I've added a note about angular-touch in the readme. It's worth loading the unminified version of angular when encountering these kinds of problems. The error messages tend to be less cryptic :)

**Comment by circlingthesun** [comment]
You should also probably be loading a es6 polyfill such as https://github.com/paulmillr/es6-shim or you might experience issues on older browsers.
