### ISSUE TITLE
ngTouch is required ?

### ISSUE THREAD

**Issue by auban** [circlingthesun/angular-foundation-6#49]
Hello,

I have update angular foundation from 0.10.25 to 0.11.5.
I have no load ngTouch.

Is ngTouch required for orbit or is it possible for you to inject ngTouch manually with $inject and check if the module ngTouch is loaded.

Thanks

**Comment by circlingthesun** [comment]
You need to load angular-touch via script tags or your module loader after loading angular. Like so:

```htm
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.10/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.10/angular-touch.js"></script>
```

Orbit will inject ngTouch when it is loaded. So there is no need to inject anything yourself.

**Comment by circlingthesun** [comment]
I'm closing this, as I'm assuming you fixed your issue.
