### ISSUE TITLE
Button toggle css active class issue

### ISSUE THREAD

**Issue by victorsosa** [circlingthesun/angular-foundation-6#5]
The active class doesn't exist in Foundation. We can use Hollow or Disabled to emulated this. (Prefer 'hollow'), because of that actually the toggle effect is not working right now using the btnRadio.

```
.constant('buttonConfig', {
    activeClass: 'active',
    toggleEvent: 'click'
})

```
angular-foundation-6/src/buttons/buttons.js 

Note: let me know about this change, because PR is coming.

**Comment by circlingthesun** [comment]
Hey @victorsosa, you are right. It appears that the active style has been removed from Foundation 6 in order to keep the framework light. I don't think adding hollow or disabled classes is a good work around. I'll welcome a PR that'll enable you to specify your own active class :)

**Comment by victorsosa** [comment]
well the idea, is not to add anything; both class hollow and disabled are in foundation.

You can check hollow here: http://foundation.zurb.com/sites/docs/button.html

**Comment by circlingthesun** [comment]
I had a look at .hollow and it looks looks like a sensible default. Let me have you PR :)
