### ISSUE TITLE
Accordion events

### ISSUE THREAD

**Issue by celticdarren** [circlingthesun/angular-foundation-6#50]
Hi,

Is there a way to catch when an accordion title has been clicked open/close it?

Thanks, Darren.

**Comment by circlingthesun** [comment]
Not as far as I recall. I imagine emitting en event could be useful. PRs are welcome ;)

**Comment by celticdarren** [comment]
Thanks for getting back to me.

I found this:
https://github.com/circlingthesun/angular-foundation-6/pull/31/commits

Not sure if this is what I need...sounds pretty similar but insure how this can be used.

Thanks, Darren.

**Comment by celticdarren** [comment]
Didn't mean to close! Ha

**Comment by circlingthesun** [comment]
Ha, yes, I forgot about that PR. So basically, in Angular events propagate up from child scopes to parent scopes. So you can listen for that event in any parent scope or on $rootScope via the $on() function on the scope. Have a look at https://toddmotto.com/all-about-angulars-emit-broadcast-on-publish-subscribing/

**Comment by circlingthesun** [comment]
So you'll need to listen for 'down.af.accordionGroup' and 'up.af.accordionGroup'.

**Comment by celticdarren** [comment]
That's perfect. 
Thanks very much. P.S love the repo!

....And I actually mean to close this now!
