### ISSUE TITLE
Disable Desktop Carousel Swipe Event

### ISSUE THREAD

**Issue by tristolliday** [circlingthesun/angular-foundation-6#54]
The Carousel element has a strange feature when swiping on desktop where it seems to stick to the mouse. Is there a way to disable swiping on desktop devices?

**Comment by circlingthesun** [comment]
There is no way to do this currently. I'll be willing to accept a PR that adds an attribute to disable swiping. However, determining what qualifies as a "desktop device" would be better left to the application consuming the library.

**Comment by tristolliday** [comment]
Cool, i will close the issue and see if I can make something PR-able,

Many thanks -  great library!
