### ISSUE TITLE
Minifying and mangling causes ngTouch to be misnamed

### ISSUE THREAD

**Issue by suavelizard** [circlingthesun/angular-foundation-6#56]
When minifying; the orbit component cannot find ngTouch since it is not annotated. 

`Error: [$injector:unpr] Unknown provider: eProvider <- e`

**Comment by circlingthesun** [comment]
If you are using the source you should first run it through ng-annotate or the angularjs-annotate babel plugin.

**Comment by suavelizard** [comment]
Hello thanks for the reply, I am using ngAnnotate but turns out it wasn't annotating the $modal's controller function in the example.

Thanks again!
