### ISSUE TITLE
[gh-pages] Demo page doesn't work due to missing `index.js`

### ISSUE THREAD

**Issue by farrago** [circlingthesun/angular-foundation-6#72]
The demo at http://circlingthesun.github.io/angular-foundation-6/ is currently broken.

PR #66 created a new `index.js` file for all the local demo JS (which was previously inline in the `index.html`).

This has not been copied over to the `gh-pages` branch and is therefore not found when the page tries to load it, which breaks the whole page.

Adding the new index.js to gh-pages should fix it.

**Comment by notbear** [comment]
@farrago what about creating a PR if you already investigated the problem and know the solution?

**Comment by farrago** [comment]
Took a bit longer to get to than I'd hoped, but I've done one now.

The confusion was that changes to the dist directory are usually left out of PRs to make them easier to review, but I hadn't realized that the `index.js` not being added would stop it getting copied across to `gh-pages`.  Obviously, as the file wasn't in the PR, @circlingthesun also couldn't see it to remind me to add it.  Anyway, hopefully this fix will sort it out.

**Comment by circlingthesun** [comment]
@farrago thanks for taking care of that.
